### ISSUE TITLE
Rotations possibility ?

### ISSUE THREAD

**Issue by mb93** [RussCoder/djvujs#11]
Hi,
Thank you for the library, very impressive and useful with new browsers... 
Now, I have no issue but a request:
Is it possible to add an optional rotation parameter (values: 0, 90,180,270) to loadDocumentByUrl function ?
Example: loadDocumentByUrl("a.djvu",90) to load and display a.djvu with a 90° rotation.
It would be very helpful.

**Comment by RussCoder** [comment]
Hello!

Thank you for your feedback. Yes, I have already thought about such an option before. I think I will add a new control element to the control panel to allow a user to change the orientation of a page. And then I will add an additional program API allowing to pass a configuration object to the constructor or to a special method, and the object will be just a plain set of option, e.g. initial scale value, initial page number, the orientation etc. 

I'm not sure when I will do it, but it won't take much time. Maybe in a couple of days, maybe in a couple of weeks. All in all, I will write here when I do something. 

And, by the way, there is a default orientation encoded inside the .djvu format, however, the library now just ignores it and doesn't use that information at all. I will have to fix it as well, but I don't have such a file, wherein the default orientation is different from 0. Since you asked for the feature you probably have such a file whose default orientation is different in the DjVu.js Viewer and in other .djvu viewers. If you send me such a file, I will appreciate it and it will help me to test the feature.

**Comment by mb93** [comment]
Hi,
Thank you for your quick reply.
Yes a new user control to rotate the image would be a plus for the user. But I suppose the development of this control should take some time.
For my part, having an option in loadDocumentByUrl(file,[rotation parameter])  will be enough to use your plugin.

Yes, technically we  can modify the rotation directly in the djvu file( by modifying the byte x21) but
to keep the integrity  of the file, it's not possible.

As requested please find attached djvu file examples:
- file rotate90.djvu : need to be rotated 90
- file rotate180.djvu : need to be rotated 180°
- file rotate270.djvu  Need to be rotated 270°.

And  the same djvu files where the rotation was done in the byte x21:
-file  rotate90_rotatedviabyte_hex21.djvu : 90° rotation
-file  rotate180_rotatedviabyte_hex21.djvu :  180° rotation
-file  rotate270_rotatedviabyte_hex21.djvu :  270° rotation

Attached djvu files:
[imagesDjvu_to_rotate.zip](https://github.com/RussCoder/djvujs/files/2320799/imagesDjvu_to_rotate.zip)

**Comment by RussCoder** [comment]
Thank you for the files. I have already started to work on the feature. I will write here when I do something perceptible.

**Comment by RussCoder** [comment]
I have added the new control to change the rotation of a page and extended the program API.
Now you can use:
```
DjVuViewerInstance.loadDocumentByUrl("/tmp/DjVu3Spec.djvu", { pageRotation: 90 });
```
Or its equivalent:
```
DjVuViewerInstance.loadDocumentByUrl("/tmp/DjVu3Spec.djvu").then(() => DjVuViewerInstance.configure({pageRotation: 90}));
```

The bundles are on the website or in the latest release.

I haven't changed to library yet, so it still ignores the byte flag of the rotation. 
And not your file `rotate90_rotatedviabyte_hex21.djvu` has incorrect flag, it's 4, but must be 5, as I understood from the specification. So it's not processed by a desktop viewer as well. I decided to say it just in case.

**Comment by RussCoder** [comment]
Thank you for the information. I have tested it with WinDjView 2.1. According to the specification there are only 4 values: 1, 6, 2, 5, and only these values are recognized by WinDjView. But there are mistakes in the specification. And it is not going to be hard to support 2 values for each rotation, I suppose. So I will take it into account when I start to implement the support of rotation inside the DjVu.js Library.

**Comment by RussCoder** [comment]
Hello. I've implemented the support of rotations inside the DjVu.js library. Now the library returns a rotated image by default. There is a new release, new bundles on the website and a new version of the extension for browsers.

**Comment by mb93** [comment]
Hi!
Great, thank you again for your quick intervention to solve my rotations specifities request!
I really appreciate.
Best regards.
