### ISSUE TITLE
Toolbar position at the top ?

### ISSUE THREAD

**Issue by mb93** [RussCoder/djvujs#12]
Hi Russcoder,
I'm using your library every day and it's very useful , thank you.
Would it be possible to have an option to place the toolbar at the top ( of the image) ?
Currently, the toolbar is under the image.
I always use the zoom function (+ button and -).  But when zooming, the toolbar disappears from the screen (following the resizing of the image) and i have to manually use the scrollbar to find it and to reposition the mouse on the + or -...
As I always need to zoom in successively  (2~5 times or more), it's not very practical.
If the toolbar was at the top, there would no longer be this matter.
Is it possible to have an option (like DjvuRotation)  like this for example: 
{ positionToolbar: 0|1 }  where 0=normal, 1=top ?
it would be great ;)

**Comment by RussCoder** [comment]
Hello!

I think it's not difficult to add such an option. However, I didn't understand completely what kind of a problem you have. 

The toolbar is always attached to the bottom of the viewer, and when you resize the image (by the way, you can do it with Ctrl+Scroll, not only with -/+ buttons on the toolbar), it remains at its place. The viewer should't be out of it's block and the toolbar and the footer line should be always be at the same place. Or you are speaking about zooming of the whole web page? But even in this case, everything should be ok, and the toolbar should be always in sight. 

Can you send me a screenshot of the problem which you have? It would help me to understand it better.

**Comment by mb93** [comment]
Hi,
Thank you for quick reply
In fact, i was using this code for loading page and to have a full page mode:

[page.zip](https://github.com/RussCoder/djvujs/files/2693968/page.zip)

You can see directly what i said in this html sample with zooming effect...

Since your answer, i've added your main.css  of djvu.js.org and the problem has disappeared but the image is not in full page anymore. 
The new html code:
[page2.zip](https://github.com/RussCoder/djvujs/files/2694018/page2.zip)

But it requires to click on button to switch in full page mode now...

So this second solution is enough...  But how can i initialize the plugin in full page mode ? Is there an option to force the display in full mode page in loadDocumentByUrl() function ?

Thank you!

**Comment by RussCoder** [comment]
Hello, @mb93 !

I see. You don't need the styles from djvu.js.org. You need the styles of DjVu.js Browser Extension which is always in "in the full-page mode". It's not actually in this mode, but the full-page has no effect since the block, which the viewer renders in, has already taken the whole page. You may install the extension and see the styles in the dev tools or in the extension directory of the repository https://github.com/RussCoder/djvujs/blob/master/extension/viewer.html

For brevity, instead of the styles from djvu.js.org, you should just add the following styles to your page.html 

```html
<style>
        html, body, #for_viewer {
            height: 100% !important;
            margin: 0;
            padding: 0;
            font-family: sans-serif;
        }
</style>
```

It will make the body of the document and the container block be exactly of the size of the window. The last entry with the font-family may be omitted actually. This is the very styles which are used in case of the browser extension.

Thus, remove

```html
<link rel="stylesheet" href="https://djvu.js.org/css/main.css?v=1"/>
```
from your page and add the styles which fix the size of the container block. 

If you still need an option to turn on and off the full page mode programmatically, let me know.

**Comment by mb93** [comment]
Hi Russcoder,
It been fixed my problem.
Thank you very much for your quick help!
Best regards.
