### ISSUE TITLE
Public library files are not working

### ISSUE THREAD

**Issue by grigoni** [RussCoder/djvujs#23]
Hi RussCoder
your work on DjVu format is really welcome, thank you a LOT!
I think the JS technology will be the best option for this document format

it looks that files delivered from an Italian online library (http://emeroteca.braidense.it) are not working even when the file is downloaded locally. it would be great in the future to use your browser extension instead of the actually unsupported plugins.
link to the single document:
http://emeroteca.braidense.it/export/gea/172/FASC_52542.djvu

link to the web page
http://emeroteca.braidense.it/gea/indice_giorni.php?IDTestata=172&CodScheda=00FJ&Alph=C&OB=titolo&OM=&SearchString=&SearchField=&PageRec=25&PageSel=3&PB=1&Anno=1879&Mese=12
just click on the issue identified by numbers under the column "Giorno" (day in italian.
 
my opinion is that DjVu files do contain subpages links 

thank you for any help
kind regards
Gianandrea

**Comment by RussCoder** [comment]
Hello, @grigoni !

Thank you for notifying me about the issue. 

As I see .djvu files on that website are embedded into a page using a different markup, the one I haven't thought can be used. I will take it into account and will update the extension soon, after which it will work. 

As for now, you are right, it seems that there are so called indirect djvu files - each document isn't a single file, but a bunch of files being stored in the same folder. You cannot open such a file locally from your computer even if you download one, because downloading it you just download an index file, not all the files composing the document. 

The only way to open such a file is to open it via a link by the extension. Right click on the link 
http://emeroteca.braidense.it/export/gea/172/FASC_52542.djvu
and then select the option "Open with DjVu.js Viewer" and it will work.

**Comment by grigoni** [comment]
thanks! the suggested alternative way works

**Comment by RussCoder** [comment]
Now it works in the extension v0.3.5.0.
Already available for Firefox, for Chrome will be available after their review process which may take a couple of weeks.
