### ISSUE TITLE
Browser extension doesn't work if URL parameters are present

### ISSUE THREAD

**Issue by mikeprince** [RussCoder/djvujs#25]
The Chrome browser extension does not work if the URL has parameters, and downloads the djvu file instead.
E.g. I tried a local file:///index.djvu?djvuopts&page=9.djvu&zoom=page. Without the URL parameters the file loads in the browser fine.

**Comment by RussCoder** [comment]
I detected the problem and found a solution. Will fix it in the next release. 
By the way, all arguments in the query string after `?` will be ignored. 
There is a way to set a page in a URL via adding a hash, e.g. `#page=10`.

**Comment by mikeprince** [comment]
Thanks for the quick response. Unfortunately I don't have control over the URLs in this case, but opening the document regardless will be a big help! I look forward to the next release.

**Comment by r-pankevicius** [comment]
I think it's better to stick to Content-Type: image/x.djvu header and do not require that URL ends with ".djvu".

For example, my web app has URLs like this one (note no .djvu in URL):
https://server/application/api/ArchiveDocument?county=06&document=0662-P73

I serve djvu files with headers:
Content-Type: image/x.djvu
Content-Disposition: inline; filename="06_0662-P73.djvu"; filename*=UTF-8''06_0662-P73.djvu

The reason for this URL format is that document names can contain slashes (/) and then URL routing rules are broken.

**Comment by RussCoder** [comment]
@mikeprince I have just submitted a new version (0.3.5.1) to the Google Chrome Extensions Store. After the review process, it will be published. Theoretically, it may take up to several weeks, but usually 2-3 days is enough. For Firefox the new version is already available. 

@r-pankevicius it's not that easy. Actually, this issue https://github.com/RussCoder/djvujs/issues/22 is about the same. 
To read headers of a request I will have to intercept all requests in the main frame. That means that my extension will kind of filter a big part of your traffic. Although, it shouldn't be a problem, but if I made a mistake somewhere I risk to paralyze all  your 
 navigation in the browser in some cases. So I decided to intercept only request's to `.djvu` even before they are actually made by the browser. And this feature is activated manually on the main page of the extension. That is, I chose the way of the least intervention. 

However, since you are not the first who requests such a feature, I will take another look at the API of the browser, and maybe add such a behavior as another option, or will extend the current one. But it's more related to the issue mentioned above, so I will close the current one.
