### ISSUE TITLE
Feature request: Add localization to support different languages

### ISSUE THREAD

**Issue by r-pankevicius** [RussCoder/djvujs#28]
@RussCoder , I started with localization of djvujs on my fork.

Do you consider to add this feature in main repo (this one)?

https://github.com/r-pankevicius/djvujs/issues/1

**Comment by r-pankevicius** [comment]
P.S. For a moment I have no idea how to localize help page?..

**Comment by RussCoder** [comment]
Yes, I have the plans to add the support of different languages to the viewer. 

I have looked at your code. It seems to me a bit redundant. 

I would just create a dictionary, an object with keys like "helpMessage" and values like "This a help message". Also I would add one more option and would save it as others (look for `Consts.OPTIONS_UPDATED_ACTION` - options are saved depending on whether it's an extension or just a usual web-page). Then, after the page is loaded, I would retrieve the options and expose the required dictionary via context API of React. And in components I would just use values from the dictionary, e.g. `dict.helpMessage`. That is, I see no need in a third-party library to implement this feature. 

The style `t('Options`)` is handy when there are short phrases and separate words. But for phrases like `You can click on the page number to enter it manually` it's better to use keys to my mind, and you are kind of going to use keys for long phrases in your code as I see. So maybe it's better to use keys everywhere? 

Or yes, and each dictionary should be just merged with the English one (for cases if something wasn't translated), which would be considered as a full dictionary. 

Also, I would use `.js` files for dictionaries instead of `.json` just to be able to add comments or split long strings. 

However, if you create a working version even with that third party-library, I would accept a pull request (although maybe I would edit the scheme afterwards). What I want is:

1) Everything should be translated.
2) There must be two buttons (with national flags or just names of languages) on the main page.
3) The selected language should be saved as an option (`Consts.OPTIONS_UPDATED_ACTION`).

As for language auto detection, it's a good feature, but it should be overridden if another language is saved in options. 
And I'm not sure that detection on query string is a needed feature for general case, maybe it's just better to pass an option to a viewer's constructor? Or extend the API of the viewer to change the language from the outer code?

**Comment by r-pankevicius** [comment]
@RussCoder  As for 1 day coding activity there naturally may be left overs.
Now I am on vacation, so if I will find functionality implemented by you, that's fine for me :)

**Comment by r-pankevicius** [comment]
@RussCoder Just look how it "looks natural" and after considering it's an open source project it is not.

> "I would just create a dictionary, an object with keys like "helpMessage" and values like "This a help message"

Oh, after a week you realize that you mistyped it, so you have {...helpMessage: 'This a help massage'...}

As far as I know people behaviours you will fix a message without changing a key, e.g. {...helpMessage: 'This a help message'...}

Now consider that you have to support 10 languages other than English. You don't know all of them... So how will you make sure everything is fine before your next release? Or at least how will you DETECT that some extra translation is needed?

As an opposite (CASE2), consider, you have {..."This a help massage": "This a help massage"...} translation dictionary. You are FORCED to change the wrong key itself, e.g. to {..."This a help message": "This a help message"...}.

In CASE2 you can easily set up a unit test to test if all 10 language translations are in place before release (compare if Object keys are present).

How will you track helpMessage?

**Comment by RussCoder** [comment]
An apt observation. I will think about it. 
Definitely, it's worth using short phrases as direct keys, however I'm not sure about long phrases in the help window. However, they can be split into several relatively short sentences, and each sentence can be translated separately.

**Comment by jsbien** [comment]
Google shows there is quite a lot  of localization tools for Javascript. Have you considered using one of them? I have no experience with Javascript but I have localized some programs and I know the good tool is useful :-)

**Comment by RussCoder** [comment]
@jsbien I read a bit about one tool, but I still do not see a significant need in it - it seems to me the functionality require for us can be implemented relatively easily. 
However, I'm not going to do anything within this week.

**Comment by r-pankevicius** [comment]
@jsbien There is a very different situation compared commercial product development and open source hacks. Especially it's visible in translations. As I understand you are in academia world, so probably I can tell you some secrets you did not know.

4 days ago @RussCoder  issued a new release with a comment "Fixed a bug due to which an empty DJVI chunk caused an error."

If we were only in English world, it's just as easy for an enthusiastic programmer as "fix a bug, release, here you are".

But if we consider some new text string is introduced during the fix, then release may be delayed for days, weeks, months... The more languages we support, the situation is worse. Because we need to contact every translator asking "please...".

At some initial point we may have a commercial company interested in our work and committed to their customers to do the translation (I am in this position trying to push Swedish translation). But if my company releases some product based on this and, say, I go to work somewhere else, it's all broken. No one will take care of Swedish translations anymore, because that version my company got works as expected.

So, after all, it's not about localization software available, it's all about people, about setting the rules that can keep our work going...

**Comment by jsbien** [comment]
Some time ago I used https://crowdin.com/project/codepoints, cf. https://github.com/Codepoints/Codepoints.net/issues/74/ It was a quite convenient tool suggesting sensible equivalents. I don't know whether something similar is available for Javascript.

**Comment by RussCoder** [comment]
@r-pankevicius @jsbien 

I have added the multi language support.
You can create your own dictionaries according to this guide
https://github.com/RussCoder/djvujs/blob/master/TRANSLATION.md

**Comment by r-pankevicius** [comment]
@RussCoder Could you write how to customize viewer so I can pass desired language as parameter?

loadOptions function in rootSaga will set it to according to navigator.languages, but I need to enforce it because I know the language in advance. 

Language is decide in our web apps earlier in the flow, users already are in the needed language context when they click links to view archive images (djvu), so I need to pass the language as a param, not as browser string.

For example, passing language option in Viewer ctor in HTML page:

window.viewer = window.DjVuViewerInstance = new window.DjVu.Viewer({language: 'ru', fallbackLanguage: 'en'});

**Comment by RussCoder** [comment]
@r-pankevicius 

Now you can pass `{language: 'ru'}` to the viewer's constructor. The same option can be added to the `configure({language: 'ru'})` method. Also there is a static method `DjVu.Viewer.getAvailableLanguages()` which returns an array of language codes which are present in the viewer. 

Haven't added it to the docs on the website, will do it later. 

The binaries can be downloaded from the last release.

**Comment by r-pankevicius** [comment]
Confirmed: new window.DjVu.Viewer({language:'ru'}) works as expected.

But I'm not closing the issue: there are some common errors to be yet localized.

For example try non existing URL in Russian viewer: window.DjVuViewerInstance.loadDocumentByUrl("http://jkdsdlfjksdlfkjlse/blahblah");

You will get semi-localized error message:
Ошибка: Web request error
An error occurred, the file wasn't loaded. The error object is printed to the browser console.

You can find places for error string (not sure if all) in this commit: https://github.com/r-pankevicius/djvujs/commit/87aa9b93a5f6ecbba83ae41639786bd83dba8032

I will not make pull request because now I have localization that's incompatible with yours.

**Comment by r-pankevicius** [comment]
@RussCoder there is a typo in Russian translation:

    "go to the previous page":
        "перейти к прейти к предыдущей странице",

**Comment by r-pankevicius** [comment]
Closing as languages' support is quite stable now.
