### ISSUE TITLE
Absolute and relative links in the table of contents do not work

### ISSUE THREAD

**Issue by jsbien** [RussCoder/djvujs#31]
Please open the first volume of a dictionary at https://djvu.szukajwslownikach.uw.edu.pl/linde-t/01/index.djvu. The links to other volumes, eg. "Tom drugi G-L", don't work.

**Comment by jsbien** [comment]
First, the links in https://djvu.szukajwslownikach.uw.edu.pl/linde-t/01/index.djvu were absolute which was a temporary solution which became obsolete. Now they contain the relative ones like the ones attached yesterday.
Secondly, the links don't work in your viewer.
Last but not least, I think your viewer should mimic the current handling of links by djview4: https://sourceforge.net/p/djvu/feature-requests/93/. I'm not familiar with other viewers.

**Comment by RussCoder** [comment]
At last, I checked how djview4 handles it and it turned out to be pretty simple - it just switches to another document (even without an option to return back).
I think I can do the same, or even better:  just open a document in another tab without closing the current one. 
And with this approach I can handle both absolute and relative links the same way.

**Comment by RussCoder** [comment]
In the new version of the extension (0.5.5.0) both types of links are supported. 
You can try it out now.

**Comment by jsbien** [comment]
On https://djvu.szukajwslownikach.uw.edu.pl/linde-t/01/index.djvu works very nice, thanks.
