### ISSUE TITLE
Import as module

### ISSUE THREAD

**Issue by bilalhodzic** [RussCoder/djvujs#34]
Is there a way I can use your code as a module in node.js? Or I need to insert your files into my project manually in one folder?

**Comment by RussCoder** [comment]
Hello! Right now there is not way to use it as a classical module (e.g. via npm). Moreover, the `djvu.js` bundle is an `iife`, not a `umd`, so you will not be able to `require()` it from your Node.js code. 

You have to clone the project, and correct `rollup.config.js` to bundle to library as a `umd` module. 

It should work on Node.js (but not completely, since it uses Canvas API for some operations), but I have never tested it myself on Node.js.

If you have some problems with creating a module from the code, write me here, I will help.
