### ISSUE TITLE
Wrong size of the "hidden text" words

### ISSUE THREAD

**Issue by lionkmp** [RussCoder/djvujs#41]
Hi RussCoder, first congratulations for this great work! Added links to my djvu.hu website! ;-) I have a project that edits DjVu in the browser, but it's outdated and requires exporting to PNG files plus XML. Could be largely improved with your APIs. ;-) https://sourceforge.net/projects/webdjvutexted/

Now the bugreport: the words in hidden text layer do not cover the bounding box of the underlying image-word, this makes text selection a bit difficult. Trying to "drag" the selection, but it's not "coming". 

A possible solution could be to add some spacing to letters so that words will be as long as the bounding box (at least as I remember I did that in my editor). 

Attached a screenshot with example. This shows that "hidden text layer" words are too short compared to visible image. Causing trouble selecting certain parts. 

![djvu-js](https://user-images.githubusercontent.com/5088657/102687096-e54c4400-41ec-11eb-9f3b-13e447995387.png)

Thank you, keep up the good work!

**Comment by RussCoder** [comment]
Hello! Thank for the bug report, but I've been known about this problem since the day I implemented the transparent text layer above the image. 

The thing is that I do not want to implement my own text selection logic now (selecting "symbols" on the canvas, redrawing the image during the movement of the cursor) and want to use the abilities of the browser. In fact, it's impossible to accurately match the text with the underlying image, just because there are usually different fonts and font sizes. 

So I decided to just match the top left corner of a word. As far as I remember, I do it only for words, not for separate symbols. 
 
By and large, it's enough to quickly select the text. In addition to this, there is a separate text view mode.

Since you reported the "bug", I will take a look again, maybe it can be somehow improved, e.g. maybe it can be scaled via `transform` css rule. However, this issue isn't of high priority.

**Comment by lionkmp** [comment]
Thank you. Yes, may be worth to keep at least as a bug report so that you can keep an eye on the problem. Longer words create bigger problem. 

I noticed it when tried to select the whole page and it kept on un-selecting. Because I was dragging beyond the end of the last "word" (of the text-overlay). Took some time to realize I need to watch for the appearing selected text, not the "image".

In my mentioned program I used an off-screen `div` to measure length or rendered text and used that to figure out a good `letter-spacing` value. I don't remember how much performance penalty that brings. I think this fits your described existing text-overlay solution. No `transform` was needed, please don't get confused on my code below link, that uses scale/transform for the whole-page only.

From line 274 in this URL, function "createBox()" routines on parameter "fit":

https://sourceforge.net/p/webdjvutexted/code/HEAD/tree/trunk/script.js#l274

if(fit) {

Might be useful, I don't know ;-)

**Comment by r-pankevicius** [comment]
@lionkmp  Regarding your first post: could you give a link to the actual djvu file you have a trouble with? Or attach it here?

**Comment by lionkmp** [comment]
@r-pankevicius  
Yes, this was in the example screenshot above:
https://c64.rulez.org/pub/c64.hu/Konyvek/basic_feladatok_tukreben_ocr.djvu

**Comment by r-pankevicius** [comment]
@lionkmp Thanks for the file. But it has 160 pages, which page would you like to mention?
 
 I downloaded your doc, looking at it using this viewer:
 
![image](https://user-images.githubusercontent.com/1467109/104106587-c27af000-52bf-11eb-88e0-1b4896aafdd9.png)

**Comment by r-pankevicius** [comment]
Ah, OK, I see that's page 3

**Comment by RussCoder** [comment]
I have implemented the trick with `letter-spacing` in the version `0.8.2`.
 
It was:
![Screenshot_107](https://user-images.githubusercontent.com/18438165/134499421-d902b546-56ed-476f-811e-6ae6f7b7bf04.png)

And it is now:

![Screenshot_108](https://user-images.githubusercontent.com/18438165/134499464-1563a0b5-6557-4dae-889a-28ec04005b30.png)

This file was used https://github.com/RussCoder/djvujs/blob/master/library/assets/djvu3spec+.djvu?raw=true

On my computer it takes about 200 ms or less to process one page. Acceptable performance.

**Comment by lionkmp** [comment]
Looks great, thank you!
