### ISSUE TITLE
Mousepad scroll fires page change

### ISSUE THREAD

**Issue by aamodio** [RussCoder/djvujs#52]
Hi RussCoder,

I'm experimenting an annoying issue: trying to scroll the page with mousepad (two fingers gesture, up and down), the djvujs viewer intercepts the command and fires the page change. Is there a way to block page this behavior? 

Thanks,
A.

**Comment by RussCoder** [comment]
Hello! 

Well, this behavior takes place in case of the single page view mode. When you continue to scroll and the page has been already scrolled to the very bottom, it will change the page. To my mind, it should make easier to turn over pages, because you do not have to move your cursor onto next/prev buttons to change the page, just continue to scroll (also arrow buttons on the keyboard also do the same). I do not think mousepad works differently.

Currently, there is no option to disable it. Do you want me to add such an option?

**Comment by aamodio** [comment]
Hi RussCoder,

yes, I think this option will be very useful. At the moment when image fits the viewport it happens to change document page trying to scroll the main html page.

Thanks.
A.

**Comment by RussCoder** [comment]
I have added a new UI option `changePageOnScroll` in the viewer v0.5.5. You need to set it to `false`.
It's described here https://djvu.js.org/downloads
