### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by Jhonny7** [RussCoder/djvujs#8]
Is it possible to create thumbnails with the library? If so, in what way can I achieve it?

**Comment by RussCoder** [comment]
What do you mean by thumbnails? 

-  thumbnails of pages in DjVu format, which are inside THUM chunks? Do you want to render them or you want to add them to a .djvu file? 
- or you are speaking about images of pages?

**Comment by Jhonny7** [comment]
yes, I just want to show the images of the pages on the side as if it were a kind of preview

**Comment by Jhonny7** [comment]
![captura](https://user-images.githubusercontent.com/17410259/37722354-6f7a4406-2cf1-11e8-8fd6-3f244562260e.JPG)

**Comment by RussCoder** [comment]
With the library it's possible to create an image of each page of a document (as DjVu.js Viewer does, the demo is here https://djvu.js.org), but since you want to show the images on the side I wonder do you speak about the Viewer itself? In the Viewer I haven't implemented such feature yet. 

If you just want to convert a .djvu document into a set of images, it may be done and I can tell you how to do it (the library produces ImageData object, which maybe rendered on the canvas element)

**Comment by Jhonny7** [comment]
I would appreciate very much if you told me where to implement the set of images that you say, and having it equal display it on the screen is not a problem

**Comment by Jhonny7** [comment]
the code you show is new truth? because I searched for it in both JS files and I do not see it

**Comment by RussCoder** [comment]
I have just written the code for you as an example showing how you can get an ImageData of each page of a .djvu document

**Comment by Jhonny7** [comment]
The closest thing I have to what you show me is:
![cercano](https://user-images.githubusercontent.com/17410259/37726128-3f0da6ec-2cfa-11e8-8e4e-e7d110e64685.JPG)

**Comment by RussCoder** [comment]
I have just written the code for you as an example showing how you can get an ImageData of each page of a .djvu document

**Comment by Jhonny7** [comment]
okok well, thank you, just a question, I understand that that code should be placed, but not knowing very well its structure I do not know where

**Comment by RussCoder** [comment]
Where? Where you wish of course. It's code using the library, you shouldn't change the code of the library of course. Maybe I didn't understand what do you want. You want to use the library in order to get images of pages, yes? I have shown how to do it in a browser script.

**Comment by Jhonny7** [comment]
Could you tell me the method in which you arm all the pages, that is, your fix, this.pages ???

**Comment by RussCoder** [comment]
A .djvu file is parsed in the constructor of the `DjVuDocument` class. More precisely, in the `init()` method. In the method, the ArrayBuffer representing the file is parsed and the array of pages is formed. Then you can look at the `DjVuPage` class to see the inner structure of a page.

**Comment by Jhonny7** [comment]
I already have the pages now I just need to know at what moment you convert the buffer or the array into an image please that would help a lot

**Comment by RussCoder** [comment]
`DjVuPage` class has a method `getImageData` - it's the very method in which the image is generated. You should invoke it without any parameters. The method automatically invokes a `decode` method, which decodes all three layers of the DjVu image in general case - a mask, a background and a foreground. Then all three layers are converted into a single `ImageData` object. Note, that after you get the image of a page, you should invoke `reset` method of the page, in order to clear all temporary objects and arrays, which are generated during the decoding. Otherwise, you may got a memory leak, so to speak. If you use `getPage` method of the `DjVuDocument`, you are not to care about resetting of each page, since the method do it automatically, when a new page is requested.

**Comment by Jhonny7** [comment]
![uly](https://user-images.githubusercontent.com/17410259/37833758-c3256168-2e71-11e8-865c-661f62ddfb70.JPG)


This is the method I use to get the imageData but when I want to show it on a canvas it appears blank or without information, could you help me with this last one? :(
